src/Entity/City.php
<?php

namespace App\Entity;

use App\Repository\CityRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CityRepository::class)]
class City
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $Name = null;

    #[ORM\Column(length: 100)]
    private ?string $Latitude = null;

    #[ORM\Column(length: 100)]
    private ?string $Longitude = null;

    #[ORM\Column(length: 5)]
    private ?string $CountryCode = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->Latitude;
    }

    public function setLatitude(string $Latitude): self
    {
        $this->Latitude = $Latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->Longitude;
    }

    public function setLongitude(string $Longitude): self
    {
        $this->Longitude = $Longitude;

        return $this;
    }

    public function getCountryCode(): ?string
    {
        return $this->CountryCode;
    }

    public function setCountryCode(string $CountryCode): self
    {
        $this->CountryCode = $CountryCode;

        return $this;
    }
	
	public function __toString()
	{
		return $this->Name;
	}
}

src/Entity/Weather.php
<?php

namespace App\Entity;

use App\Repository\WeatherRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WeatherRepository::class)]
class Weather
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $Temperature = null;

    #[ORM\Column]
    private ?float $Precipitation = null;

    #[ORM\Column]
    private ?int $OvercastLevel = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $Date = null;

    #[ORM\Column]
    private ?float $Wind = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?City $city = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTemperature(): ?float
    {
        return $this->Temperature;
    }

    public function setTemperature(float $Temperature): self
    {
        $this->Temperature = $Temperature;

        return $this;
    }

    public function getPrecipitation(): ?float
    {
        return $this->Precipitation;
    }

    public function setPrecipitation(float $Precipitation): self
    {
        $this->Precipitation = $Precipitation;

        return $this;
    }

    public function getOvercastLevel(): ?int
    {
        return $this->OvercastLevel;
    }

    public function setOvercastLevel(int $OvercastLevel): self
    {
        $this->OvercastLevel = $OvercastLevel;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getWind(): ?float
    {
        return $this->Wind;
    }

    public function setWind(float $Wind): self
    {
        $this->Wind = $Wind;

        return $this;
    }

    public function getCity(): ?city
    {
        return $this->city;
    }

    public function setCity(?city $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Form/WeatherType.php
<?php

namespace App\Form;

use App\Entity\Weather;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WeatherType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Temperature', NumberType::class)
            ->add('Precipitation', NumberType::class)
            ->add('OvercastLevel', NumberType::class)
            ->add('Date', DateTimeType::class)
            ->add('Wind', NumberType::class)
            ->add('city')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Weather::class,
        ]);
    }
}

src/Controller/WeatherController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\City;
use App\Repository\WeatherRepository;
use App\Repository\CityRepository;

class WeatherController extends AbstractController
{
    public function cityAction(City $city, WeatherRepository $weatherRepository): Response
    {
        $weathers = $weatherRepository->findByLocation($city);

        return $this->render('weather/city.html.twig', [
            'city' => $city,
            'weathers' => $weathers,
        ]);
    }

    public function cityActionByName($name, CityRepository $cityRepository, WeatherRepository $weatherRepository): Response
    {
        $weathers = $weatherRepository->findByLocationName($name);

        $cityName = $cityRepository->findOneBy(['Name' => $name]);

        return $this->render('weather/city.html.twig', [
            'city' => $cityName,
            'weathers' => $weathers
        ]);
    }
}

templates/weather/city.html.twig
{% extends 'base.html.twig' %}

{% block title %}Weather in {{city.name}}, {{city.CountryCode}} {% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ city.name }}, {{city.CountryCode}} ✅</h1>

    <ul>
		{% for weather in weathers %}
			<li>{{ weather.date|date('d.m.Y') }}: {{ weather.temperature }}&deg;</li>
		{% endfor %}
	</ul>
</div>
{% endblock %}

templates/weather/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello WeatherController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon-portable/www/pogodynka/src/Controller/WeatherController.php'|file_link(0) }}">src/Controller/WeatherController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon-portable/www/pogodynka/templates/weather/index.html.twig'|file_link(0) }}">templates/weather/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}